name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build
    - name: Deploy 🚀
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} 
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        vercel-args: '--prod' 
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
